apiVersion: v1
kind: Secret
metadata:
  name: traklead-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: traklead-redis-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
