namespace: traklead
imagePullPolicy: IfNotPresent

server:
  image:
    repository: kumama88/traklead-server
    tag: latest
  port: 9191
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1024Mi
  env:
    tenantName: "Owexa Media"
    serverUrl: "https://dashboard.owexamedia.com"
    clickServerUrl: "https://go.axpay.ink"
    tenantPartnerUrl: "https://publisher.owexamedia.com"
    tenantSupportEmail: "support@owexamedia.com"

click:
  image:
    repository: kumama88/traklead-click
    tag: latest
  port: 9292
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1024Mi
  env:
    tenantName: "Owexa Media"

postgresql:
  image:
    repository: postgres
    tag: "16-alpine"
  database: owexa_media
  username: doadmin
  password: "changeme-postgres-password"
  storage: 5Gi
  storageClassName: standard
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi

redis:
  image:
    repository: redis
    tag: "7-alpine"
  password: "changeme-redis-password"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

kafka:
  image:
    repository: apache/kafka
    tag: "3.9.0"
  storage: 5Gi
  storageClassName: standard
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1024Mi
